name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: |
          apk add ruby && gem install mustache

      - name: Create output
        run: sh ./build.sh

      - name: Push to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: "Seung-wan"
          destination-repository-name: "ssum-translate"
          user-email: ${{ secrets.EMAIL }}
          commit-message: "Auto-deploy: $(date +'%Y-%m-%d %H:%M:%S')"
          target-branch: main

      - name: Test exported variable
        run: echo "$DESTINATION_CLONED_DIRECTORY"
